language: python
python:
  - "2.7"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - coverage run tests.py
after_success:
  - codecov --token=$CODECOV_TOKEN
notifications:
  email: isidrolauscher@gmail.com
  on_success: never